# Generated by Django 5.0.2 on 2024-02-15 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=100, null=True, verbose_name='Описание')),
                ('status', models.CharField(blank=True, choices=[('new', 'Новая'), ('in_progress', 'В процессе'), ('done', 'Сделано')], max_length=30, null=True, verbose_name='Статус')),
                ('deadline', models.CharField(max_length=10, verbose_name='Дата окончания')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Время изменения')),
            ],
        ),
    ]
