# Generated by Django 5.0.2 on 2024-02-15 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='full_description',
            field=models.TextField(default=1, max_length=3000, verbose_name='Подробное описание'),
            preserve_default=False,
        ),
    ]
