# Generated by Django 5.0.2 on 2024-02-23 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_task_full_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='deadline',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Дата окончания'),
        ),
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.CharField(default=1, max_length=100, verbose_name='Описание'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='task',
            name='full_description',
            field=models.TextField(blank=True, max_length=3000, null=True, verbose_name='Подробное описание'),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('new', 'Новая'), ('in_progress', 'В процессе'), ('done', 'Сделано')], default=1, max_length=30, verbose_name='Статус'),
            preserve_default=False,
        ),
    ]
