# Generated by Django 5.0.3 on 2024-03-20 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0006_alter_task_type_old'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='types',
            field=models.ManyToManyField(blank=True, related_name='tasks', to='webapp.type', verbose_name='Типы'),
        ),
    ]
