# Generated by Django 5.0.3 on 2024-03-20 17:30

from django.db import migrations


def transfer_types(apps, schema_editor):
    Task = apps.get_model('webapp.Task')
    for task in Task.objects.all():
        task.types.add(task.type_old)

def rollback_transfer(apps, schema_editor):
    Task = apps.get_model('webapp.Task')
    for task in Task.objects.all():
        task.type = task.types.first()
        task.save()
        #task.type_old.set(task.types.all())


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0007_task_types'),
    ]

    operations = [
        migrations.RunPython(transfer_types, rollback_transfer)
    ]
