# Generated by Django 5.0.3 on 2024-03-20 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0008_auto_20240320_2330'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='type_old',
        ),
    ]
