# Generated by Django 5.0.2 on 2024-03-29 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0010_alter_task_description_alter_task_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='types',
            field=models.ManyToManyField(blank=True, null=True, related_name='tasks', to='webapp.type', verbose_name='Types'),
        ),
    ]
