# Generated by Django 5.0.2 on 2024-03-29 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0011_alter_task_types'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='types',
            field=models.ManyToManyField(related_name='tasks', to='webapp.type', verbose_name='Types'),
        ),
    ]
