# Generated by Django 5.0.2 on 2024-04-07 10:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0012_alter_task_types'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Время изменения')),
                ('start_date', models.DateField(verbose_name='Start Date')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='End Date')),
                ('title', models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(5)], verbose_name='Title')),
                ('description', models.TextField(blank=True, max_length=3000, null=True, verbose_name='Description')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
