# Generated by Django 5.0.2 on 2024-04-07 11:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0016_alter_task_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='task',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.PROTECT, related_name='tasks', to='webapp.task', verbose_name='Tasks'),
            preserve_default=False,
        ),
    ]
