# Generated by Django 5.0.2 on 2024-04-07 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0017_project_task'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='project',
        ),
    ]
